SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (1, N'Roses', CAST(350.00 AS Decimal(6, 2)), 152, N'Benmore Florist', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (2, N'Daisy', CAST(250.00 AS Decimal(6, 2)), 500, N'Benmore Florist', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (3, N'Happy Socks', CAST(599.99 AS Decimal(6, 2)), 52, N'Benmore Florist', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (4, N'Bath and Body pamper', CAST(769.95 AS Decimal(6, 2)), 546, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (5, N'Rhys and Teddy Hamper', CAST(299.95 AS Decimal(6, 2)), 522, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (6, N'Flower Power Bouquet', CAST(349.95 AS Decimal(6, 2)), 312, N'Benmore Florist', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (7, N'Lindt Chocolate Delight', CAST(399.95 AS Decimal(6, 2)), 21, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (8, N'Giant Cupcake', CAST(499.95 AS Decimal(6, 2)), 564, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (9, N'Handsome Snack Tin', CAST(299.95 AS Decimal(6, 2)), 2, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (10, N'Pretzels and Beer Crate', CAST(389.95 AS Decimal(6, 2)), 252, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (11, N'Backpack Cooler', CAST(399.95 AS Decimal(6, 2)), 321, N'Benmore Florist', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (12, N'Gift Box', CAST(699.95 AS Decimal(6, 2)), 100, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (13, N'Gold Drip Cake', CAST(799.95 AS Decimal(6, 2)), 321, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (14, N'Snack Attack', CAST(399.95 AS Decimal(6, 2)), 321, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (15, N'Husband Bro Bucket', CAST(299.99 AS Decimal(6, 2)), 50, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (16, N'Thank You Cookie Tin', CAST(269.95 AS Decimal(6, 2)), 48, N'Pick ''n Pay', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (17, N'Jack Daniels', CAST(599.95 AS Decimal(6, 2)), 100, N'Pick ''n Pay Liquor', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (18, N'Jagermeister', CAST(499.95 AS Decimal(6, 2)), 6514, N'Pick ''n Pay Liquor', <Binary Data>)
INSERT INTO [dbo].[Product] ([ProductID], [Name], [Price], [Quantity], [Supplier], [Image]) VALUES (21, N'asdas', CAST(32.00 AS Decimal(6, 2)), 24, N'wr', <Binary Data>)
SET IDENTITY_INSERT [dbo].[Product] OFF
